version: 2
updates:

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "slackapi/slack-github-action"
        update-types: ["version-update:semver-major"]
