name: PR Notification

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    uses: your-org/main-repo/.github/workflows/pr-to-slack.yml@main
    with:
      channel-id: 'YOUR_CHANNEL_ID'  # Can be different per repo
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }} 