name: PR Slack Notification

on:
  pull_request:
    types: [opened, assigned]

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auto-assign PR to author if unassigned
        if: github.event.pull_request.assignee == null
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [context.payload.pull_request.user.login]
            })
        
      - name: Get Slack User ID
        id: get-slack-id
        run: |
          # Since author is most likely the assignee, we can just use the assignee directly
          GITHUB_USER="${{ github.event.pull_request.user.login }}"
          SLACK_ID=$(jq -r --arg user "$GITHUB_USER" '.[$user] // ""' .github/workflows/github-slack-mapping.json)
          echo "slack_id=$SLACK_ID" >> $GITHUB_OUTPUT
          echo "github_user=$GITHUB_USER" >> $GITHUB_OUTPUT

      - name: Send Slack notification
        id: slack-notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'C08DDF685GC'
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<${{ github.event.pull_request.html_url }}>"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Author:* ${{ steps.get-slack-id.outputs.slack_id && format('<@{0}>', steps.get-slack-id.outputs.slack_id) || steps.get-slack-id.outputs.github_user }}\n*Reviewers:* ${{ github.event.pull_request.requested_reviewers != null && github.event.pull_request.requested_reviewers.length > 0 && join(github.event.pull_request.requested_reviewers.*.login, ', ') || 'None' }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Send reviewer reminder
        if: github.event.pull_request.requested_reviewers == null || github.event.pull_request.requested_reviewers.length == 0
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'C08DDF685GC'
          payload: |
            {
              "thread_ts": "${{ steps.slack-notification.outputs.thread_ts }}",
              "text": "<@${{ steps.get-slack-id.outputs.slack_id }}> Please add reviewers to your PR"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }} 