name: PR Slack Notification

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Get Slack User ID
        id: get-slack-id
        run: |
          # Get author's Slack ID
          AUTHOR=$(jq -r --arg user "${{ github.event.pull_request.user.login }}" \
            'if has($user) then "<@" + .[$user] + ">" else $user end' \
            .github/workflows/github-slack-mapping.json)
          echo "author=$AUTHOR" >> $GITHUB_OUTPUT

          # Get reviewers' Slack IDs
          REVIEWERS=$(jq -r --argjson users '${{ toJSON(github.event.pull_request.requested_reviewers.*.login) }}' \
            '$users[] as $u | if has($u) then "<@" + .[$u] + ">" else $u end | @csv' \
            .github/workflows/github-slack-mapping.json | sed 's/"//g')
          echo "reviewers=$REVIEWERS" >> $GITHUB_OUTPUT

      - name: Send Slack notification
        id: slack-notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'C08DDF685GC'
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Pull request opened in `${{ github.event.repository.name }}`\n<${{ github.event.pull_request.html_url }}|#${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}>:"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Author:* ${{ steps.get-slack-id.outputs.author }}\n*Reviewers:* ${{ steps.get-slack-id.outputs.reviewers || 'None' }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Send reviewer reminder
        if: github.event.pull_request.requested_reviewers == null || github.event.pull_request.requested_reviewers.length == 0
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'C08DDF685GC'
          payload: |
            {
              "thread_ts": "${{ steps.slack-notification.outputs.thread_ts }}",
              "text": "${{ steps.get-slack-id.outputs.author }} Please add reviewers to your PR"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }} 