name: PR Workflow

on:
  pull_request:
    types: [opened, reopened, review_requested]
  pull_request_target:
    types: [closed]

jobs:
  notify:
    uses: otimlabs/actions/.github/workflows/pr-base.yml@julian/workflow-call-secrets
    secrets: inherit